routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/blog', 'BlogController@index');
Route::get('/blog/{slug}', 'BlogController@show');

Route::get('/best-seo-services-in-delhi', function () {
    return view('seo');
})->name('seo');

Route::get('/social-media-marketing-services-in-delhi', function () {
    return view('social');
})->name('social');

Route::get('/ppc-services-in-delhi', function () {
    return view('ppc');
})->name('ppc');

Route::get('/website-designing-in-delhi', function () {
    return view('web-design');
})->name('web-design');

Route::get('/website-development-in-delhi', function () {
    return view('web-develop');
})->name('web-develop');

Route::get('my-posts', 'PostController@myPosts');
Route::resource('posts','PostController');
Route::get('contact-us', 'EnquiryController@index');
Route::post('contact-us', ['as'=>'contactus.store','uses'=>'EnquiryController@contactUSPost']);

Route::group(['prefix' => 'cp/posts'], function () {
    Route::get('/', 'PostController@index');
    Route::match(['get', 'post'], 'create', 'PostController@create');
    Route::match(['get', 'put'], 'update/{id}', 'PostController@update');
    Route::delete('delete/{id}', 'PostController@delete');
});

Route::group(['prefix' => 'cp/enquiries'], function () {
    Route::get('/', 'EnquiryController@list');
    //Route::delete('delete/{id}', 'EnquiryController@delete');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cp', 'HomeController@index')->name('home');
Route::get('/cp/services', 'ServiceController@index')->name('cp-services');
Route::get('/cp/blog', 'BlogController@index')->name('cp-blog');
Route::get('/cp/blog/create', 'BlogController@create')->name('cp-blog-create');
Route::post('/cp/blog/create', 'BlogController@store')->name('cp-blog-store');

resources/views/blog-detail.blade.php
@extends('layouts.external')
@section('title', $post->slug)
@section('content')
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">{{$post->title}}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-bottom:40px">
                <div class="panel" style="font-family:arial;min-height:80px;border-radius:3px;padding:20px;min-height:650px;">
                    <h3>{{$post->title}}</h3>
                    <p style="color:#888">Last updated on {{date_format($post->updated_at, 'F d, Y')}} by {{$post->user->name}}</p>
                    <img src="{{asset('img/posts')}}/{{$post->image}}" style="width:100%;margin-bottom:16px;" >
                    <p>{{$post->description}}</p>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/blog.blade.php
@extends('layouts.external')
@section('title', 'Blog - Sidak Singh')
@section('content')
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Blog</h2>
            </div>
        </div>
        <div class="row">
            @foreach($posts as $post)
            <div class="col-md-6" style="margin-bottom:40px">
                <div class="panel" style="border:1px solid #F80; font-family:arial;min-height:80px;border-radius:3px;padding:20px;min-height:650px;">
                    <h3>{{$post->title}}</h3>
                    <p style="color:#888">Last updated on {{date_format($post->updated_at, 'F d, Y')}} by {{$post->user->name}}</p>
                    <img src="img/posts/{{$post->image}}" style="width:100%;margin-bottom:16px;" >
                    <p>{{$post->description}}</p>
                    <a class="btn btn-danger btn-block text-white" href="{{url('/blog') .'/'. $post->slug}}">Continue reading...</a>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</section>
@endsection

resources/views/contactUs.blade.php
@extends('layouts.external')
@section('title', 'Blog - Sidak Singh')
@section('content')
<section>
    <div class="container">
        <h1>Contact US Form</h1>
 
@if(Session::has('success'))
   <div class="alert alert-success">
     {{ Session::get('success') }}
   </div>
@endif
 
{!! Form::open(['route'=>'contactus.store']) !!}
 
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
{!! Form::label('Name:') !!}
{!! Form::text('name', old('name'), ['class'=>'form-control', 'placeholder'=>'Enter Name']) !!}
<span class="text-danger">{{ $errors->first('name') }}</span>
</div>
 
<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
{!! Form::label('Email:') !!}
{!! Form::text('email', old('email'), ['class'=>'form-control', 'placeholder'=>'Enter Email']) !!}
<span class="text-danger">{{ $errors->first('email') }}</span>
</div>

<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
{!! Form::label('Mobile:') !!}
{!! Form::text('mobile', old('mobile'), ['class'=>'form-control', 'placeholder'=>'Enter Mobile Number']) !!}
<span class="text-danger">{{ $errors->first('mobile') }}</span>
</div>
 
<div class="form-group {{ $errors->has('message') ? 'has-error' : '' }}">
{!! Form::label('Message:') !!}
{!! Form::textarea('message', old('message'), ['class'=>'form-control', 'placeholder'=>'Enter Message']) !!}
<span class="text-danger">{{ $errors->first('message') }}</span>
</div>
 
<div class="form-group">
<button class="btn btn-success">Contact US!</button>
</div>
 
{!! Form::close() !!}
 
</div>
        </div>
    </div>
</section>
@endsection

resources/views/create.blade.php
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

<div class="modal-dialog" role="document">

<div class="modal-content">

<div class="modal-header">

<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

<h4 class="modal-title" id="myModalLabel">Create Item</h4>

</div>

<div class="modal-body">



<form data-toggle="validator" action="{{ route('posts.store') }}" method="POST">

<div class="form-group">

<label class="control-label" for="title">Title:</label>

<input type="text" name="title" class="form-control" data-error="Please enter title." required />

<div class="help-block with-errors"></div>

</div>

<div class="form-group">

<label class="control-label" for="title">Description:</label>

<textarea name="details" class="form-control" data-error="Please enter details." required></textarea>

<div class="help-block with-errors"></div>

</div>

<div class="form-group">

<button type="submit" class="btn crud-submit btn-success">Submit</button>

</div>

</form>

</div>

</div>

</div>

</div>

resources/views/edit.blade.php
<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

<div class="modal-dialog" role="document">

<div class="modal-content">

<div class="modal-header">

<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

<h4 class="modal-title" id="myModalLabel">Edit Item</h4>

</div>

<div class="modal-body">



<form data-toggle="validator" action="/item-ajax/14" method="put">

<div class="form-group">

<label class="control-label" for="title">Title:</label>

<input type="text" name="title" class="form-control" data-error="Please enter title." required />

<div class="help-block with-errors"></div>

</div>

<div class="form-group">

<label class="control-label" for="title">Description:</label>

<textarea name="details" class="form-control" data-error="Please enter details." required></textarea>

<div class="help-block with-errors"></div>

</div>

<div class="form-group">

<button type="submit" class="btn btn-success crud-submit-edit">Submit</button>

</div>

</form>



</div>

</div>

</div>

</div>

resources/views/home.blade.php
@extends('layouts.cp')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/my-posts.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laravel 5.5 Ajax CRUD Example</title>
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css">
</head>
<body>
	<div class="container">
		<div class="row">
		    <div class="col-lg-12 margin-tb">
		        <div class="pull-left">
		            <h2>Laravel 5.5 Ajax CRUD Example Demo</h2>
		        </div>
		        <div class="pull-right">
				<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">Create New Post</button>
		        </div>
		    </div>
		</div>
		<table class="table table-bordered">
			<thead>
			    <tr>
				<th>Title</th>
				<th>Details</th>
				<th width="200px">Action</th>
			    </tr>
			</thead>
			<tbody>
			</tbody>
		</table>

		<ul id="pagination" class="pagination"></ul>

		<!-- Create Item Modal -->
		@include('create')
		<!-- Edit Item Modal -->
		@include('edit')
	</div>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.3.1/jquery.twbsPagination.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

	<script type="text/javascript">
		var url = "<?php echo route('posts.index')?>";
	</script>
	<script src="/js/postsAjax.js"></script> 
</body>
</html>

resources/views/ppc.blade.php
@extends('layouts.external')
@section('title', 'ppc packages in Delhi, India')
@section('content')
<section>
  <div class="container" style="min-height:500px">
    <div class="row">
      <div class="col-md-12">
        <h1 class="section-heading text-uppercase">ppc packages in Delhi, India</h1>
        <p class="seo">Boost the queries and sales by Advertising your business through PPC (Pay per Click). It recommends multiple solutions and approaches to appear on the most commonly used search engines list like Google, Yahoo, Bing and many others. It provides impressions and click only from targeted audience.</p>
      </div>
    </div>
    <div class="row">
        <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center ">Small</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item medium">
            <h2 class="list-group_item-heading text-center">Medium</h2>
          </li>
          <li href="#" class="list-group-item active" style="background-color:#0A0">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item medium">15 Keywords per month</li>
          <li class="list-group-item medium">80% keywords top 10 Guarantee</li>
          <li class="list-group-item medium">30 Directory submissions</li>
          <li class="list-group-item medium">40 Social bookmarking</li>
          <li class="list-group-item medium">5 Article Submission</li>
          <li class="list-group-item medium">5 Press Release</li>
          <li class="list-group-item medium">10 Profile Creation</li>
          <li class="list-group-item medium">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center">Business</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
    </div>
    
  </div>
</section>



@endsection

resources/views/seo.blade.php
@extends('layouts.external')
@section('title', 'Best SEO packages in Delhi, India')
@section('content')
<section>
  <div class="container" style="min-height:500px">
    <div class="row">
      <div class="col-md-12">
        <h1 class="section-heading text-uppercase">Best SEO packages in Delhi, India</h1>
        <p class="seo">Here are some of the best SEO packages in delhi India given below but firstly we should know what SEO is and how it works and why we need this for better outcome of our business.</p>
      
        <h4 class="section-heading ">What is SEO?</h4>
        <p class="seo">Search Engine Optimization (SEO) is well known for improving the rank of your website to generate more organic traffic on your website or business. This is the a simple definition of SEO by us.    </p>
        
        <h4 class="section-heading ">How SEO works?</h4>
        <p class="seo">SEO is a very complicated and intresting thing which consists of many small-small things like: On page optimization, Off page optimization, Creating backlinks, Social bookmarking, Article submission, brand awareness by posting comments and many more things else. </p>

        <h4 class="section-heading ">What is the use of SEO?</h4>
        <p class="seo">Search Engine Optimization (SEO) is well known for improving the rank of your website to generate more organic traffic on your website or business. This is the as simple definition of SEO by us.    </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center ">Small</h4>
          </li>
          <li href="#" class="list-group-item active">INR 5,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">05 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">20 Directory submissions</li>
          <li class="list-group-item list-group-item-info">25 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">4 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">2 Blog</li>
         </ul><br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item medium">
            <h2 class="list-group_item-heading text-center">Medium</h2>
          </li>
          <li href="#" class="list-group-item active" style="background-color:#0A0">INR 8,000 / Month + 18% GST</li>
          <li class="list-group-item medium">10 Keywords per month</li>
          <li class="list-group-item medium">80% keywords top 10 Guarantee</li>
          <li class="list-group-item medium">30 Directory submissions</li>
          <li class="list-group-item medium">35 Social bookmarking</li>
          <li class="list-group-item medium">5 Article Submission</li>
          <li class="list-group-item medium">5 Press Release</li>
          <li class="list-group-item medium">10 Profile Creation</li>
          <li class="list-group-item medium">3 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center">Business</h4>
          </li>
          <li href="#" class="list-group-item active">INR 12,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">40 Directory submissions</li>
          <li class="list-group-item list-group-item-info">45 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">15 Profile Creation</li>
          <li class="list-group-item list-group-item-info">5 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
    </div>
    
  </div>
</section>



@endsection

resources/views/social.blade.php
@extends('layouts.external')
@section('title', 'Social Media Marketing & Optimization')
@section('content')
<section>
  <div class="container" style="min-height:500px">
    <div class="row">
      <div class="col-md-12">
        <h1 class="section-heading text-uppercase">Social Media Marketing & Optimization</h1>
        <p class="seo">A business needs a good identity and social reorganization for its growth and that comes only with SMO. Social Media Optimization offers a platform where you can share the information about your company and products/services.
It always target organic audience and interested individuals.</p>
      </div>
    </div>
    <div class="row">
    <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center ">Small</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item medium">
            <h2 class="list-group_item-heading text-center">Medium</h2>
          </li>
          <li href="#" class="list-group-item active" style="background-color:#0A0">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item medium">15 Keywords per month</li>
          <li class="list-group-item medium">80% keywords top 10 Guarantee</li>
          <li class="list-group-item medium">30 Directory submissions</li>
          <li class="list-group-item medium">40 Social bookmarking</li>
          <li class="list-group-item medium">5 Article Submission</li>
          <li class="list-group-item medium">5 Press Release</li>
          <li class="list-group-item medium">10 Profile Creation</li>
          <li class="list-group-item medium">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center">Business</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
    </div>
    
  </div>
</section>



@endsection

resources/views/web-design.blade.php
@extends('layouts.external')
@section('title', 'Best Web Designing packages in Delhi, India')
@section('content')
<section>
  <div class="container" style="min-height:500px">
    <div class="row">
      <div class="col-md-12">
        <h1 class="section-heading text-uppercase">Best Website Designing packages in Delhi, India</h1>
        <p class="seo">SEO Services controls and regulates the leads and organic search of the business. It is the strategic procedure of granting a high position to any website on the search engine results. SEO services consist of many matchless techniques that design and develop your website to advance its appearance and make it search engine welcoming. We are well aware about the algorithms that search engines utilize and what ways the visitors used to find out the information on the sites.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center ">Small</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul><br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item medium">
            <h2 class="list-group_item-heading text-center">Medium</h2>
          </li>
          <li href="#" class="list-group-item active" style="background-color:#0A0">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item medium">15 Keywords per month</li>
          <li class="list-group-item medium">80% keywords top 10 Guarantee</li>
          <li class="list-group-item medium">30 Directory submissions</li>
          <li class="list-group-item medium">40 Social bookmarking</li>
          <li class="list-group-item medium">5 Article Submission</li>
          <li class="list-group-item medium">5 Press Release</li>
          <li class="list-group-item medium">10 Profile Creation</li>
          <li class="list-group-item medium">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
      <div class="col-md-4 text-center">
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <h4 class="list-group_item-heading text-center">Business</h4>
          </li>
          <li href="#" class="list-group-item active">INR 10,000 / Month + 18% GST</li>
          <li class="list-group-item list-group-item-info">15 Keywords per month</li>
          <li class="list-group-item list-group-item-info">80% keywords top 10 Guarantee</li>
          <li class="list-group-item list-group-item-info">30 Directory submissions</li>
          <li class="list-group-item list-group-item-info">40 Social bookmarking</li>
          <li class="list-group-item list-group-item-info">5 Article Submission</li>
          <li class="list-group-item list-group-item-info">5 Press Release</li>
          <li class="list-group-item list-group-item-info">10 Profile Creation</li>
          <li class="list-group-item list-group-item-info">1 Blog</li>
         </ul> <br>
         <a class="btn btn-danger btn-lg text-white" href="tel:9911665256">Call us here:- 9911665256</a>
      </div>
    </div>
    
  </div>
</section>



@endsection